# Generated by Django 5.2.5 on 2025-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cart_items/"),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="cart",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
