# Generated by Django 5.2.5 on 2025-08-31 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_image_cart_session_key_alter_cart_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="image",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cart",
            name="item_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[("food", "Food"), ("drink", "Drink")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user_session",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
