# Generated by Django 5.2.5 on 2025-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.CharField(default="static/images/momo.jpg", max_length=255),
        ),
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
