# Generated by Django 5.2.5 on 2025-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_food_image_alter_food_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
